In [1]:
from pathlib import Path
from urllib.parse import urlparse

import pandas as pd
import requests
import re
import time

In [2]:
# Find project root automatically
# Expected structure:
#
# ROOT/
# ├── .github/workflows/
# ├── 42/dataset/workflow_security_labels.csv
# └── scripts/download_workflows.ipynb

current = Path.cwd().resolve()

ROOT_DIR = None

for candidate in [current, *current.parents]:
    labels_path = (
        candidate
        / "42"
        / "dataset"
        / "workflow_security_labels.csv"
    )

    if labels_path.exists():
        ROOT_DIR = candidate
        break

if ROOT_DIR is None:
    raise FileNotFoundError(
        "Could not find 42/dataset/workflow_security_labels.csv"
    )


DATASET_DIR = ROOT_DIR / "42" / "dataset"

LABELS_CSV = (
    DATASET_DIR
    / "workflow_security_labels.csv"
)

URLS_CSV = (
    DATASET_DIR
    / "workflow_urls.csv"
)

OUTPUT_DIR = (
    ROOT_DIR
    / ".github"
    / "workflows"
)

FAILURES_CSV = (
    DATASET_DIR
    / "workflow_download_failures.csv"
)


OUTPUT_DIR.mkdir(
    parents=True,
    exist_ok=True
)


print("ROOT_DIR   :", ROOT_DIR)
print("LABELS_CSV :", LABELS_CSV)
print("URLS_CSV   :", URLS_CSV)
print("OUTPUT_DIR :", OUTPUT_DIR)

ROOT_DIR   : /home/huawei/BOOSTSECURITY/42
LABELS_CSV : /home/huawei/BOOSTSECURITY/42/42/dataset/workflow_security_labels.csv
URLS_CSV   : /home/huawei/BOOSTSECURITY/42/42/dataset/workflow_urls.csv
OUTPUT_DIR : /home/huawei/BOOSTSECURITY/42/.github/workflows

In [3]:
df = pd.read_csv(LABELS_CSV)

if "workflow_blob_url" not in df.columns:
    raise ValueError(
        "Column 'workflow_blob_url' not found."
    )


workflow_urls = (
    df[["workflow_blob_url"]]
    .dropna()
    .copy()
)


workflow_urls["workflow_blob_url"] = (
    workflow_urls["workflow_blob_url"]
    .astype(str)
    .str.strip()
)


workflow_urls = workflow_urls[
    workflow_urls["workflow_blob_url"] != ""
]


workflow_urls = (
    workflow_urls
    .drop_duplicates()
    .reset_index(drop=True)
)


workflow_urls.to_csv(
    URLS_CSV,
    index=False
)


print("Total label rows :", len(df))
print("Unique workflows :", len(workflow_urls))
print("Saved to         :", URLS_CSV)

workflow_urls.head()

Total label rows : 2431
Unique workflows : 474
Saved to         : /home/huawei/BOOSTSECURITY/42/42/dataset/workflow_urls.csv

                                   workflow_blob_url
0  https://github.com/microsoft/ignite25-LAB506-m...
1  https://github.com/cloudposse-terraform-compon...
2  https://github.com/run-llama/liteparse/blob/a6...
3  https://github.com/fortinet-fortisoar/connecto...
4  https://github.com/fabric8io/kubernetes-client...

In [4]:
def github_to_raw_url(url):
    """
    Convert:

    https://github.com/owner/repo/blob/SHA/.github/workflows/test.yml

    to:

    https://raw.githubusercontent.com/owner/repo/SHA/.github/workflows/test.yml
    """

    parsed = urlparse(url)

    if parsed.netloc == "raw.githubusercontent.com":
        return url


    parts = parsed.path.strip("/").split("/")


    if (
        parsed.netloc not in {
            "github.com",
            "www.github.com"
        }
        or len(parts) < 5
        or parts[2] != "blob"
    ):
        raise ValueError(
            f"Invalid GitHub workflow URL: {url}"
        )


    owner = parts[0]
    repo = parts[1]
    ref = parts[3]

    file_path = "/".join(
        parts[4:]
    )


    return (
        f"https://raw.githubusercontent.com/"
        f"{owner}/{repo}/{ref}/{file_path}"
    )

In [5]:
def sanitize_filename(value):
    return re.sub(
        r"[^A-Za-z0-9._-]+",
        "-",
        str(value)
    ).strip("-")


def make_filename(url):
    """
    Example:

    https://github.com/cloudposse/test-helpers/blob/SHA/.github/workflows/test.yml

    becomes:

    cloudposse-test-helpers-test.yml
    """

    parsed = urlparse(url)

    parts = parsed.path.strip("/").split("/")

    if len(parts) < 5 or parts[2] != "blob":
        raise ValueError(
            f"Invalid GitHub workflow URL: {url}"
        )

    owner = sanitize_filename(parts[0])
    repo = sanitize_filename(parts[1])

    workflow_path = "/".join(parts[4:])

    original_filename = Path(
        workflow_path
    ).name

    original_filename = sanitize_filename(
        original_filename
    )

    return (
        f"{owner}-"
        f"{repo}-"
        f"{original_filename}"
    )

In [6]:
used_filenames = set()

filenames = []


for url in workflow_urls["workflow_blob_url"]:

    filename = make_filename(url)


    # If the same filename occurs more than once,
    # add part of the commit SHA
    if filename in used_filenames:

        parsed = urlparse(url)

        parts = parsed.path.strip("/").split("/")

        ref = parts[3]

        path = Path(filename)

        filename = (
            f"{path.stem}-"
            f"{ref[:8]}"
            f"{path.suffix}"
        )


        # Extra protection against another collision
        counter = 2

        while filename in used_filenames:

            filename = (
                f"{path.stem}-"
                f"{ref[:8]}-"
                f"{counter}"
                f"{path.suffix}"
            )

            counter += 1


    used_filenames.add(
        filename
    )

    filenames.append(
        filename
    )


workflow_urls = workflow_urls.copy()

workflow_urls[
    "filename"
] = filenames


print(
    "Unique workflow URLs:",
    len(workflow_urls)
)

print(
    "Unique filenames:",
    workflow_urls[
        "filename"
    ].nunique()
)


workflow_urls.head()

Unique workflow URLs: 474
Unique filenames: 474

,workflow_blob_url,filename
0,https://github.com/microsoft/ignite25-LAB506-m...,microsoft-ignite25-LAB506-migrate-and-moderniz...
1,https://github.com/cloudposse-terraform-compon...,cloudposse-terraform-components-aws-dms-iam-au...
2,https://github.com/run-llama/liteparse/blob/a6...,run-llama-liteparse-ocr_servers.yml
3,https://github.com/fortinet-fortisoar/connecto...,fortinet-fortisoar-connector-netscaler-adc-pyt...
4,https://github.com/fabric8io/kubernetes-client...,fabric8io-kubernetes-client-build.yml

In [7]:
MAX_RETRIES = 4

downloaded = 0
skipped = 0
failed = 0

failures = []


session = requests.Session()

session.headers.update(
    {
        "User-Agent":
        "github-actions-workflow-downloader"
    }
)


total = len(
    workflow_urls
)


for i, row in workflow_urls.iterrows():

    number = i + 1

    url = row[
        "workflow_blob_url"
    ]

    filename = row[
        "filename"
    ]

    output_path = (
        OUTPUT_DIR
        / filename
    )


    # Already downloaded
    if output_path.exists():

        skipped += 1

        print(
            f"[{number}/{total}] "
            f"SKIP   {filename}"
        )

        continue


    try:

        raw_url = github_to_raw_url(
            url
        )

    except Exception as e:

        failed += 1

        failures.append(
            {
                "workflow_blob_url": url,
                "filename": filename,
                "error": str(e)
            }
        )

        print(
            f"[{number}/{total}] "
            f"FAILED {filename}: {e}"
        )

        continue


    success = False
    last_error = None


    for attempt in range(
        1,
        MAX_RETRIES + 1
    ):

        try:

            response = session.get(
                raw_url,
                timeout=(10, 60)
            )


            response.raise_for_status()


            OUTPUT_DIR.mkdir(
                parents=True,
                exist_ok=True
            )


            output_path.write_bytes(
                response.content
            )


            downloaded += 1
            success = True


            print(
                f"[{number}/{total}] "
                f"OK     {filename}"
            )

            break


        except requests.HTTPError as e:

            last_error = e


            # Do not retry 404
            if (
                e.response is not None
                and
                e.response.status_code == 404
            ):
                break


        except (
            requests.ConnectionError,
            requests.Timeout
        ) as e:

            last_error = e


        except Exception as e:

            last_error = e

            break


        if attempt < MAX_RETRIES:

            wait = attempt * 2

            print(
                f"[{number}/{total}] "
                f"RETRY  {filename}"
            )

            time.sleep(
                wait
            )


    if not success:

        failed += 1

        failures.append(
            {
                "workflow_blob_url": url,
                "raw_url": raw_url,
                "filename": filename,
                "error": str(last_error)
            }
        )


        print(
            f"[{number}/{total}] "
            f"FAILED {filename}: "
            f"{last_error}"
        )

[1/474] OK     microsoft-ignite25-LAB506-migrate-and-modernize-windows-and-sql-server-workloads-to-azure-add-to-project.yml
[2/474] OK     cloudposse-terraform-components-aws-dms-iam-automerge.yml
[3/474] OK     run-llama-liteparse-ocr_servers.yml
[4/474] OK     fortinet-fortisoar-connector-netscaler-adc-pytest_checks.yml
[5/474] OK     fabric8io-kubernetes-client-build.yml
[6/474] OK     es-shims-all-node-tens.yml
[7/474] OK     aziontech-lib-code-review.yml
[8/474] OK     adafruit-Adafruit_CircuitPython_SCD30-failure-help-text.yml
[9/474] OK     Tencent-TencentKona-21-build-cross-compile.yml
[10/474] OK     cloudposse-terraform-components-aws-dns-primary-release.yml
[11/474] OK     turbot-steampipe-plugin-crtsh-golangci-lint.yml
[12/474] OK     salesforcecli-plugin-template-sf-test.yml
[13/474] OK     canonical-kepler-rocks-pull_request.yaml
[14/474] OK     AdobeDocs-audience-manager.ja-JP-assign-issue.yml
[15/474] OK     Hapag-Lloyd-.github-stale.yml
[16/474] OK     nextcloud-event_update_notification-appstore-build-publish.yml
[17/474] OK     simp-pupmod-simp-sudo-pr_tests.yml
[18/474] OK     AdobeDocs-analytics.es-ES-assign-issue.yml
[19/474] OK     rapidsai-cuml-test.yaml
[20/474] OK     cloudposse-terraform-components-aws-ec2-client-vpn-chatops.yml
[21/474] OK     cloudposse-test-helpers-validate-codeowners.yml
[22/474] OK     AdobeDocs-marketo-developer.de-DE-assign-pr.yml
[23/474] OK     ocicl-invistra-main.yml
[24/474] OK     cloudposse-terraform-components-aws-eks-storage-class-chatops.yml
[25/474] OK     fortify-fortify-ssc-parser-burp-update-repo-docs.yml
[26/474] OK     turbot-steampipe-mod-gcp-compliance-sync-labels.yml
[27/474] OK     turbot-steampipe-plugin-ibm-registry-publish.yml
[28/474] OK     simp-pupmod-simp-simp_grub-validate_tokens.yml
[29/474] OK     fortinet-fortisoar-connector-one-identity-pytest_checks.yml
[30/474] OK     oracle-devrel-platform-migration-group-license_audit.yml
[31/474] OK     Automattic-jetpack-error-autotagger.yml
[32/474] OK     simp-pupmod-simp-simp_ds389-validate_tokens.yml
[33/474] OK     simp-pupmod-simp-clamav-validate_tokens.yml
[34/474] OK     canonical-ngc-integrator-operator-on_pull_request.yaml
[35/474] OK     tesseract-ocr-tesseract-unittest.yml
[36/474] OK     aws-amplify-amplify-flutter-rest_xml_v2.yaml
[37/474] OK     canonical-cert-manager-rock-pull_request.yaml
[38/474] OK     canonical-libvpl-tools-debian-packaging-pr-draft.yml
[39/474] OK     canonical-metallb-rocks-pull_request.yaml
[40/474] OK     canonical-checkbox-daily-builds.yml
[41/474] OK     canonical-sriov-dpdk-rocks-pull_request.yaml
[42/474] OK     ocicl-cl-string-match-main.yml
[43/474] OK     simp-pupmod-simp-nfs-validate_tokens.yml
[44/474] OK     Sundsvallskommun-api-service-citizen-changes-dependabot-reviewer.yml
[45/474] OK     libbpf-vmlinux.h-vmlinux.h.yml
[46/474] OK     sigstore-fulcio-verify-k8s.yml
[47/474] OK     Ericsson-cognitive-labs-on-pages.yaml
[48/474] OK     philips-software-roslyn-analyzers-cd.yml
[49/474] OK     cloudposse-terraform-aws-ec2-bastion-server-branch.yml
[50/474] OK     bcgov-nr-waste-plus-pr-open.yml
[51/474] OK     ocicl-btrie-main.yml
[52/474] OK     nationalarchives-tna-child-archives-inspire-deploy-code-website.yaml
[53/474] OK     Sundsvallskommun-api-service-installation-dependabot-reviewer.yml
[54/474] OK     turbot-flowpipe-mod-teams-stale.yml
[55/474] OK     databricks-industry-solutions-toxicity-detection-in-gaming-integration-test-aws-push.yml
[56/474] OK     turbot-steampipe-plugin-pipes-golangci-lint.yml
[57/474] OK     stolostron-backplane-operator-handle-onboard-request.yml
[58/474] OK     zopefoundation-zope.browser-pre-commit.yml
[59/474] OK     simp-pupmod-simp-simp_options-validate_tokens.yml
[60/474] OK     AudioReach-audioreach-pulseaudio-plugin-pre_merge_build.yml
[61/474] OK     oracle-devrel-tech-content-heatwave-banned_file_changes_pr.yml
[62/474] OK     envoyproxy-envoy-mobile-ios_build.yml
[63/474] OK     cloudposse-terraform-components-aws-glue-connection-branch.yml
[64/474] OK     notofonts-lao-build.yaml
[65/474] OK     minder-load-tests-demo-go-935-build-binary-signed-ghat.yml
[66/474] OK     oclif-plugin-command-snapshot-test.yml
[67/474] OK     turbot-steampipe-plugin-linode-add-issue-to-project.yml
[68/474] OK     rapidsai-legate-boost-build.yaml
[69/474] OK     Automattic-jetpack-protect-status-autotagger.yml
[70/474] OK     dpc-sdp-tide_demo_content-build.yml
[71/474] OK     Azure-azureml-oss-models-MLFlow-nghuyong-ernie-3.0-base-zh.yml
[72/474] OK     AdobeDocs-experience-manager-document-security.fr-FR-assign-issue.yml
[73/474] OK     envoyproxy-envoy-mobile-format.yml
[74/474] OK     hashicorp-hcp-terraform-operator-dependabot-pr.yaml
[75/474] OK     jaraco-jaraco.zstd-main.yml
[76/474] OK     simp-pupmod-simp-simp_ipa-validate_tokens.yml
[77/474] OK     canonical-velero-rocks-pull_request.yaml
[78/474] OK     fivetran-dbt_pardot_source-auto-release.yml
[79/474] OK     spring-projects-spring-aot-smoke-tests-3.0.x-boot-custom-banner.yml
[80/474] OK     ory-homebrew-oathkeeper-licenses.yml
[81/474] OK     huggingface-transformers-self-scheduled-amd-mi210-caller.yml
[82/474] OK     amd-ZenDNN-pytorch-pull.yml
[83/474] OK     zopefoundation-zope.app.http-pre-commit.yml
[84/474] OK     Azure-terraform-azurerm-avm-ptn-alz-connectivity-hub-and-spoke-vnet-pr-check.yml
[85/474] OK     microsoft-symphony-workflow.pr.bicep.yml
[86/474] OK     adafruit-Adafruit_CircuitPython_BLE_Heart_Rate-failure-help-text.yml
[87/474] OK     microsoft-aitour-azure-openai-assistants-auto_add_to_project.yml
[88/474] OK     puppetlabs-puppetlabs-selinux_core-unit_tests.yaml
[89/474] OK     aio-libs-aiohttp-debugtoolbar-ci.yml
[90/474] OK     microsoft-ignite25-LAB587-windows-365-ai-lab-improved-windows-search-and-click-to-do-in-action-add-to-project.yml
[91/474] OK     jenkinsci-ant-plugin-cd.yaml
[92/474] OK     simp-pupmod-simp-vsftpd-tag_deploy.yml
[93/474] OK     symfony-sms77-notifier-close-pull-request.yml
[94/474] OK     rocket-pool-lighthouse-publish-crate.yml
[95/474] OK     openjdk-wakefield-build-cross-compile.yml
[96/474] OK     signalapp-Signal-Calling-Service-ci.yml
[97/474] OK     puppetlabs-puppetlabs-stdlib-nightly.yml
[98/474] OK     envoyproxy-envoy-openssl-envoy-prechecks.yml
[99/474] OK     HDFGroup-hdfview-release.yml
[100/474] OK     ory-summit-platform-conventional_commits.yml
[101/474] OK     ory-client-ruby-licenses.yml
[102/474] OK     AdobeDocs-workfront.zh-Hans-assign-pr.yml
[103/474] OK     zopencommunity-sudoport-build_and_test.yml
[104/474] OK     getsentry-sentry-capacitor-update-deps.yml
[105/474] OK     AdobeDocs-ffs-audio-video-API-lint.yml
[106/474] OK     docker-build-push-action-.e2e-run.yml
[107/474] OK     hashicorp-hcp-terraform-operator-dependabot-pr-a82dbaa3.yaml
[108/474] OK     pulumi-pulumi-digitalocean-test.yml
[109/474] OK     ubuntu-swell-foop-build.yml
[110/474] OK     oracle-devrel-incubator-template-repolinter.yml
[111/474] OK     notofonts-linear-a-build.yaml
[112/474] OK     sunpy-sunpy-ci.yml
[113/474] OK     oracle-devrel-save-the-wildlife-license_audit.yml
[114/474] OK     SAP-neonbee-commitlint.yml
[115/474] OK     galacticcouncil-blockscout-frontend-project-management.yml
[116/474] OK     dpc-sdp-tide_authenticated_content-merge_to_reference.yml
[117/474] OK     minder-load-tests-demo-go-818-build-binary-unsigned.yml
[118/474] OK     Geonovum-HR-CRS-Gebruik-main.yml
[119/474] OK     nvm-sh-nvm-shellcheck.yml
[120/474] OK     salesforcecli-plugin-orchestrator-test.yml
[121/474] OK     simp-pupmod-simp-swap-pr_tests.yml
[122/474] OK     ministryofjustice-hmpps-electronic-monitoring-data-insights-api-pipeline.yml
[123/474] OK     adafruit-Adafruit_CircuitPython_TLC5947-build.yml
[124/474] OK     simp-pupmod-simp-simp_banners-tag_deploy.yml
[125/474] OK     turbot-steampipe-plugin-equinix-steampipe-anywhere.yml
[126/474] OK     ory-hydra-client-php-conventional_commits.yml
[127/474] OK     discourse-discourse-categories-tracking-toggle-discourse-theme.yml
[128/474] OK     ocicl-cl-sat-main.yml
[129/474] OK     Hapag-Lloyd-Renovate-Global-Configuration-welcome_message.yml
[130/474] OK     pulumi-pulumi-fastly-test.yml
[131/474] OK     salesforcecli-plugin-limits-test.yml
[132/474] OK     spring-projects-spring-aot-smoke-tests-3.2.x-framework-websocket-undertow.yml
[133/474] OK     ocicl-ansi-test-harness-main.yml
[134/474] OK     microsoft-fabriccatalyst-fabric_get_git_credentials.yml
[135/474] OK     cisagov-skeleton-tf-module-codeql-analysis.yml
[136/474] OK     youtube-cobalt_sandbox-android.yaml
[137/474] OK     ocicl-jp-numeral-main.yml
[138/474] OK     oracle-devrel-terraform-oci-arch-iot-streaming-repolinter.yml
[139/474] OK     simp-pupmod-simp-tpm-validate_tokens.yml
[140/474] OK     simp-pupmod-simp-logrotate-validate_tokens.yml
[141/474] OK     openstreetmap-openstreetmap-website-danger.yml
[142/474] OK     aws-amplify-amplify-flutter-amplify_analytics_pinpoint_example.yaml
[143/474] OK     konveyor-release-tools-collect-stale-history.yml
[144/474] OK     googleapis-google-cloud-cpp-test-runner.yml
[145/474] OK     minder-load-tests-demo-go-598-build-image-signed-ghat-malicious.yml
[146/474] OK     canonical-turtlebot3c-snap-monthly.yaml
[147/474] OK     simp-pupmod-simp-deferred_resources-tag_deploy.yml
[148/474] OK     oracle-devrel-terraform-oci-cloudbricks-redis-license_audit.yml
[149/474] OK     ocicl-clinenoise-main.yml
[150/474] OK     open-telemetry-opentelemetry-java-instrumentation-build-pull-request.yml
[151/474] OK     oracle-devrel-oci-sdk-python-samples-banned_file_changes_pr.yml
[152/474] OK     envoyproxy-envoy-mobile-android_build.yml
[153/474] OK     Sundsvallskommun-api-service-byggr-integrator-codeql.yml
[154/474] OK     cloudposse-terraform-components-aws-eks-actions-runner-controller-chatops.yml
[155/474] OK     kyma-project-keda-manager-pull-release-1.9.yaml
[156/474] OK     USGS-R-ds-gitflows-FlowChar-collaborator_contributes.yml
[157/474] OK     cloudposse-terraform-aws-ssm-tls-self-signed-cert-release.yml
[158/474] OK     opensearch-project-dashboards-anywhere-os-osd-deployment-scheduled.yml
[159/474] OK     ministryofjustice-hmpps-nomis-mapping-service-pipeline.yml
[160/474] OK     ocicl-asdf-manager-main.yml
[161/474] OK     oracle-devrel-terraform-oci-arch-embedded-finance-repolinter.yml
[162/474] OK     WordPress-Learn-content-checklist-from-comment.yml
[163/474] OK     openjdk-riscv-port-build-cross-compile.yml
[164/474] OK     upbound-terraform-provider-azuread-issue-comment-created.yaml
[165/474] OK     ory-oathkeeper-client-php-licenses.yml
[166/474] OK     aws-aws-encryption-sdk-dafny-pull.yml
[167/474] OK     DEFRA-ffc-pay-alerting-main.yml
[168/474] OK     ory-resilient-axios-conventional_commits.yml
[169/474] OK     ory-homebrew-kratos-conventional_commits.yml
[170/474] OK     Azure-terraform-azapi-hybridcontainerservice-pr-check.yaml
[171/474] OK     udacity-DroidTermsExample-APK-manual.yml
[172/474] OK     adafruit-Adafruit_CircuitPython_Prompt_Toolkit-build.yml
[173/474] OK     adafruit-Adafruit_CircuitPython_Nunchuk-failure-help-text.yml
[174/474] OK     discourse-discourse-theme-hibiscus-d-compat-branch.yml
[175/474] OK     cachix-install-nix-action-test-per-system.yml
[176/474] OK     r-lib-tree-sitter-r-publish.yaml
[177/474] OK     adafruit-Adafruit_CircuitPython_BME680-build.yml
[178/474] OK     cloudposse-terraform-components-aws-sftp-chatops.yml
[179/474] OK     bcgov-nr-rec-signage-pr-open.yml
[180/474] OK     fortinet-fortisoar-connector-datadog-siem-cloud-pytest_checks.yml
[181/474] OK     gbv-reposis_iai-maven-publish-release.yml
[182/474] OK     wp-cli-embed-command-issue-triage.yml
[183/474] OK     turbot-steampipe-mod-zoom-compliance-stale.yml
[184/474] OK     simp-pupmod-simp-rkhunter-validate_tokens.yml
[185/474] OK     turbot-steampipe-mod-gcp-labels-add-issue-to-project.yml
[186/474] OK     minder-load-tests-demo-go-249-build-image-signed-ghat-malicious.yml
[187/474] OK     microsoft-ignite25-LAB582-windows-365-deployment-lab-cloud-native-zero-trust-fully-ready-add-to-project.yml
[188/474] FAILED ministryofjustice-hmpps-person-on-probation-user-api-pipeline.yml: 404 Client Error: Not Found for url: https://raw.githubusercontent.com/ministryofjustice/hmpps-person-on-probation-user-api/9bab80973db531fb94cfb7390cebf0d45a815cab/.github/workflows/pipeline.yml
[189/474] OK     saagarjha-Ensemble-release.yml
[190/474] OK     LinkedInLearning-advanced-kotlin-database-development-2500683-main.yml
[191/474] OK     cloudposse-terraform-aws-cloudfront-s3-cdn-chatops.yml
[192/474] OK     stolostron-config-policy-controller-sonarcloud.yml
[193/474] OK     RedHatInsights-insights-results-aggregator-exporter-linters.yaml
[194/474] OK     Tencent-ncnn-visionos.yml
[195/474] OK     discourse-discourse-homepage-feature-component-discourse-theme.yml
[196/474] OK     openjdk-amber-build-cross-compile.yml
[197/474] OK     pulumi-pulumi-auth0-prerelease.yml
[198/474] OK     stolostron-backplane-operator-handle-onboard-request-464bf54a.yml
[199/474] OK     Geonovum-dso-cim-pdc-main.yml
[200/474] OK     udacity-ios-nd-persistence-manual.yml
[201/474] OK     turbot-flowpipe-mod-openai-stale.yml
[202/474] OK     notofonts-thaana-build.yaml
[203/474] OK     simp-pupmod-simp-vnc-pr_tests.yml
[204/474] OK     ljharb-find-value-locations-node-twenties.yml
[205/474] OK     DEFRA-ffc-pay-submission-main.yml
[206/474] OK     simp-pupmod-simp-simp_apache-tag_deploy.yml
[207/474] OK     elastic-ml-cpp-backport.yml
[208/474] OK     turbot-steampipe-plugin-zoom-add-issue-to-project.yml
[209/474] OK     isaacs-resolve-import-ci.yml
[210/474] OK     ocicl-nyaml-main.yml
[211/474] OK     cloudposse-terraform-aws-inspector-chatops.yml
[212/474] OK     Geonovum-dso-cim-bhkv-build.yml
[213/474] OK     cloudposse-terraform-null-smtp-mail-release.yml
[214/474] OK     Geonovum-3d-tiling-build.yml
[215/474] OK     jenkinsci-jmh-report-plugin-jenkins-security-scan.yml
[216/474] OK     npm-hosted-git-info-release.yml
[217/474] OK     npm-map-workspaces-post-dependabot.yml
[218/474] OK     oracle-devrel-terraform-oci-arch-elastic-repolinter.yml
[219/474] OK     canada-ca-terraform-modules-terraform-azurerm-caf-runbook-documentation.yml
[220/474] OK     helsingborg-stad-render-blade-view-release.yml
[221/474] OK     ocicl-cl-db3-main.yml
[222/474] OK     oracle-devrel-terraform-oci-arch-cockroachdb-license_audit.yml
[223/474] OK     kyma-project-serverless-pull.yaml
[224/474] OK     cds-snc-ui-automate-s3-backup.yml
[225/474] OK     discourse-discourse-highlightjs-structured-text-discourse-theme.yml
[226/474] OK     rapidsai-nx-cugraph-test.yaml
[227/474] OK     ocicl-cl-buchberger-main.yml
[228/474] OK     aws-deadline-deadline-cloud-for-after-effects-on_opened_pr.yml
[229/474] OK     es-shims-Math.asinh-node-tens.yml
[230/474] OK     sunpy-sunpy-ci-6e0b503f.yml
[231/474] OK     sourcegraph-terraform-aws-executors-pr-auditor.yml
[232/474] OK     ocicl-defrest-main.yml
[233/474] OK     canonical-smartctl-exporter-snap-promote.yaml
[234/474] OK     socketry-async-http-faraday-test-external.yaml
[235/474] OK     kyma-project-application-connector-manager-cra.yaml
[236/474] OK     oracle-devrel-oci-infra-automation-scripts-repolinter.yml
[237/474] OK     ocicl-sequence-iterators-main.yml
[238/474] OK     auth0-go-jwt-middleware-lint.yaml
[239/474] OK     es-shims-Map.prototype.getOrInsertComputed-node-aught.yml
[240/474] OK     Azure-azureml-oss-models-cross-encoder-ms-marco-minilm-l-6-v2.yml
[241/474] OK     USGS-R-ds-gitflows-mfmeyer-collaborator_contributes.yml
[242/474] OK     oracle-devrel-terraform-oci-blender-license_audit.yml
[243/474] OK     cloudposse-terraform-components-aws-glue-connection-release.yml
[244/474] OK     nasa-gcn-architect-functions-search-publish.yml
[245/474] OK     openjdk-wakefield-build-cross-compile-040cc7ae.yml
[246/474] OK     AudioReach-audioreach-graphservices-pre_merge_build.yml
[247/474] OK     adafruit-Adafruit_CircuitPython_FXAS21002C-release_gh.yml
[248/474] OK     oracle-devrel-oci-arch-virtual-disk-import-banned_file_changes_pr.yml
[249/474] OK     ocicl-cl-tar-file-main.yml
[250/474] OK     ministryofjustice-hmpps-sharepoint-discovery-pipeline.yml
[251/474] OK     pulumi-pulumi-pagerduty-community-moderation.yml
[252/474] OK     Kong-kong-pongo-docker.yml
[253/474] OK     falcosecurity-libs-release-body.yml
[254/474] OK     adafruit-Adafruit_CircuitPython_FocalTouch-build.yml
[255/474] OK     turbot-steampipe-plugin-whois-add-issue-to-project.yml
[256/474] OK     minder-load-tests-demo-go-979-build-binary-signed-ghat-malicious.yml
[257/474] OK     fortinet-fortisoar-connector-microsoft-sccm-pytest_checks.yml
[258/474] OK     aws-samples-amazon-chime-voiceconnector-cdr-processing-pull-request-lint.yml
[259/474] OK     Adyen-adyen-apex-api-library-unit-tests.yml
[260/474] OK     cloudflare-workers-webpack-example-semgrep.yml
[261/474] OK     canonical-velero-rocks-pull_request-40a9c527.yaml
[262/474] OK     Forsakringskassan-rimfrost-framework-handlaggning-adapter-bundle-maven-lib-ci.yaml
[263/474] OK     oracle-devrel-image-classification-digital-assistant-genai-repolinter.yml
[264/474] OK     ocicl-form-fiddle-main.yml
[265/474] OK     ory-homebrew-kratos-licenses.yml
[266/474] OK     rapidsai-cudf-pr_issue_status_automation.yml
[267/474] OK     facebookresearch-fairseq2-ci_lint_sh.yaml
[268/474] OK     facebookincubator-Facebook-Pixel-for-Wordpress-main.yml
[269/474] OK     Geonovum-GeoBIM_BIM_naar_Geo-main.yml
[270/474] OK     minder-load-tests-demo-go-863-build-image-signed-ghat-static.yml
[271/474] OK     fortinet-fortisoar-connector-cisco-umbrella-enforcement-pytest_checks.yml
[272/474] OK     numpy-numpy-user-dtypes-ci.yml
[273/474] OK     AOMediaCodec-libavif-ci-c-warnings.yml
[274/474] OK     cloudposse-terraform-aws-efs-backup-branch.yml
[275/474] OK     oracle-devrel-oci-rust-getting-started-license_audit.yml
[276/474] OK     aws-amplify-amplify-flutter-rest_xml_v1.yaml
[277/474] OK     minder-load-tests-demo-go-807-build-image-signed-ghat-static-copied.yml
[278/474] OK     ory-oathkeeper-client-ruby-licenses.yml
[279/474] OK     RegioneER-parer-dpi-compile.yml
[280/474] OK     ipfs-go-ipfs-pq-go-test.yml
[281/474] OK     adafruit-Adafruit_CircuitPython_BMP5xx-build.yml
[282/474] OK     ocicl-cl-cxx-main.yml
[283/474] OK     redhat-et-edge-pipelines-for-model-validation-test-all.yml
[284/474] OK     canonical-sdcore-router-k8s-operator-1_5_scheduled_runs.yaml
[285/474] OK     aerospike-aerospike-client-python-dev-workflow-p2.yml
[286/474] OK     fedspendingtransparency-usaspending-api-pull-request-checks.yaml
[287/474] OK     notofonts-tai-le-build.yaml
[288/474] OK     konflux-ci-crossplane-components-fullsend.yaml
[289/474] OK     ministryofjustice-hmpps-external-movements-api-pipeline.yml
[290/474] OK     Automattic-jetpack-analyzer-autotagger.yml
[291/474] OK     RedHatQuickCourses-rcb-demo-1-pr.yml
[292/474] OK     ubuntu-gnome-hitori-build.yml
[293/474] OK     Sundsvallskommun-api-service-case-data-dependabot-reviewer.yml
[294/474] OK     ljharb-call-bind-rebase.yml
[295/474] OK     puppetlabs-puppetlabs-augeas_core-unit_tests.yaml
[296/474] OK     puppetlabs-puppetlabs-yumrepo_core-daily_unit_tests_with_nightly_puppet_gem.yaml
[297/474] OK     City-of-Helsinki-drupal-helfi-etusivu-test.yml
[298/474] OK     discourse-discourse-livestream-discourse-plugin.yml
[299/474] OK     apple-swift-algorithms-pull_request.yml
[300/474] OK     MicrosoftDocs-office-docs-powershell-AutoLabelAssign.yml
[301/474] OK     sindresorhus-math-average-main.yml
[302/474] OK     cloudposse-terraform-aws-iam-user-chatops.yml
[303/474] OK     BBN-Q-QGL-actions_test.yml
[304/474] OK     kyma-project-serverless-pull-9490671e.yaml
[305/474] OK     googleapis-google-cloud-cpp-bigquery-test-runner.yml
[306/474] OK     zopefoundation-zope.vocabularyregistry-pre-commit.yml

In [8]:
print()
print("Download summary")
print("----------------")

print(
    "Unique workflows :",
    len(workflow_urls)
)

print(
    "Downloaded       :",
    downloaded
)

print(
    "Skipped existing :",
    skipped
)

print(
    "Failed           :",
    failed
)

print()
print(
    "Output directory :",
    OUTPUT_DIR
)

Download summary
----------------
Unique workflows : 474
Downloaded       : 472
Skipped existing : 0
Failed           : 2

Output directory : /home/huawei/BOOSTSECURITY/42/.github/workflows

In [9]:
failures_df = pd.DataFrame(
    failures
)


if not failures_df.empty:

    failures_df.to_csv(
        FAILURES_CSV,
        index=False
    )

    print(
        "Failures saved to:",
        FAILURES_CSV
    )

else:

    print(
        "No download failures."
    )


failures_df

Failures saved to: /home/huawei/BOOSTSECURITY/42/42/dataset/workflow_download_failures.csv

,workflow_blob_url,raw_url,filename,error
0,https://github.com/ministryofjustice/hmpps-per...,https://raw.githubusercontent.com/ministryofju...,ministryofjustice-hmpps-person-on-probation-us...,404 Client Error: Not Found for url: https://r...
1,https://github.com/Azure/terraform-azure-avm-u...,https://raw.githubusercontent.com/Azure/terraf...,Azure-terraform-azure-avm-utl-compute-windowsv...,404 Client Error: Not Found for url: https://r...

In [10]:
downloaded_files = sorted(
    list(
        OUTPUT_DIR.glob("*.yml")
    )
    +
    list(
        OUTPUT_DIR.glob("*.yaml")
    )
)


print(
    "Workflows currently in "
    ".github/workflows:",
    len(downloaded_files)
)

Workflows currently in .github/workflows: 472